<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Encounter results, the transactional outbox, idempotency records and the
 * Messenger transport table.
 *
 * The encounter table is the highest-growth table in the schema. It is created
 * here unpartitioned and is the first candidate for monthly range partitioning
 * on created_at when volume justifies it; see docs/data-model.md section 6.
 */
final class Version20260803082057 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Encounter results, outbox, idempotency records and Messenger transport';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE encounter (id UUID NOT NULL, character_id UUID NOT NULL, definition_id VARCHAR(120) NOT NULL, seed BIGINT NOT NULL, ruleset_version VARCHAR(20) NOT NULL, input_snapshot JSON NOT NULL, log BYTEA NOT NULL, outcome VARCHAR(20) NOT NULL, rounds INT NOT NULL, rewards JSON NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_encounter_character_id ON encounter (character_id)');
        $this->addSql('CREATE INDEX idx_encounter_created_at ON encounter (created_at)');
        $this->addSql('CREATE TABLE idempotency_record (idempotency_key VARCHAR(128) NOT NULL, account_id UUID NOT NULL, request_hash VARCHAR(64) NOT NULL, response JSON NOT NULL, status INT NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (idempotency_key))');
        $this->addSql('CREATE INDEX idx_idempotency_created_at ON idempotency_record (created_at)');
        $this->addSql('CREATE TABLE outbox (id UUID NOT NULL, event_type VARCHAR(120) NOT NULL, payload JSON NOT NULL, occurred_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, published_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, attempts INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_outbox_unpublished ON outbox (occurred_at) WHERE (published_at IS NULL)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE encounter ADD CONSTRAINT fk_encounter_character_id FOREIGN KEY (character_id) REFERENCES game_character (id) ON DELETE CASCADE');

        // Hand-written: DBAL has no first-class CHECK support and does not
        // introspect them, so these survive future migrations:diff runs.
        $this->addSql('ALTER TABLE encounter ADD CONSTRAINT ck_encounter_rounds_positive CHECK (rounds >= 1)');
        $this->addSql('ALTER TABLE outbox ADD CONSTRAINT ck_outbox_attempts_non_negative CHECK (attempts >= 0)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE encounter DROP CONSTRAINT fk_encounter_character_id');
        $this->addSql('DROP TABLE encounter');
        $this->addSql('DROP TABLE idempotency_record');
        $this->addSql('DROP TABLE outbox');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
